import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

interface Account {
  address: string;
  publicKey: string;
}

export default function Home() {
  const [account, setAccount] = useState<Account | null>(null);
  useEffect(() => {
    bootstrapAsync();
  }, []);

  const bootstrapAsync = async () => {
    const status = await (window as any).aptos.isConnected();
    if (status) {
      const accountAddress = await (window as any).aptos.account();
      setAccount(accountAddress);
    }
  };

  const connectWallet = async () => {
    (window as any).aptos
      .connect()
      .then((result: Account) => setAccount(result))
      .catch((err: any) => console.log(err));
  };

  const onLogin = () => {
    if (account) {
      fetch(`/api/user/${account.address}`)
        .then((res) => res.json())
        .then(async (data) => {
          console.log(data);
          const signedTransaction = await (window as any).aptos.signMessage({
            message: `Sign account with nonce ${data.nonce}`,
            nonce: data.nonce,
            address: true,
            application: true,
            chainId: true,
          });
          console.log(signedTransaction);
          fetch("/api/user/login", {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              address: account.address,
              signature: signedTransaction.signature,
              fullMessage: signedTransaction.fullMessage,
              publicKey: account.publicKey,
            }),
          });
        });
    }
  };

  const disconnectWallet = async () => {
    await (window as any).aptos.disconnect();
    setAccount(null);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>One Click Login Aptos Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to One Click Login Aptos Example
        </h1>
        {!account && (
          <button className="btn" onClick={connectWallet}>
            Connect
          </button>
        )}
        {account && (
          <button className="btn" onClick={onLogin}>
            Login
          </button>
        )}
        {account && (
          <button className="btn" onClick={disconnectWallet}>
            Disconnect
          </button>
        )}
        {account && (
          <div>
            <p>Address: {account?.address}</p>
            <p>Public Key: {account?.publicKey}</p>
          </div>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
